### ISSUE TITLE
About paper authorship

### ISSUE THREAD

**Issue by lrnv** [USU-Analytics-Solution-Center/Bruno.jl#66]
I see 5 authors to the joss paper and only 4 contributors on github. It is probably fine, but i would like to know the jusitfication for the appearance of the fifth name. 

Thanks !

**Comment by mitchellpound** [comment]
The authors that aren't contributors on GitHub were invaluable in helping to design the architecture of the package and type structure as well as help on the financial theory side of the project. Though they didn't push any code to the repo directly, they often were in pair coding sessions and overall were a large reason the package works :)

**Comment by lrnv** [comment]
Thanks, this is explanation enough for me.
